# Generated by Django 2.1.15 on 2020-07-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='it资产',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('资产编号', models.CharField(max_length=50)),
                ('资产名称', models.CharField(blank=True, max_length=50, null=True)),
                ('资产类型', models.CharField(blank=True, max_length=50, null=True)),
                ('区域', models.CharField(blank=True, max_length=50, null=True)),
                ('位置', models.CharField(blank=True, max_length=50, null=True)),
                ('使用人', models.CharField(blank=True, max_length=50, null=True)),
                ('使用人部门', models.CharField(blank=True, max_length=50, null=True)),
                ('使用状态', models.CharField(max_length=50)),
                ('cpu', models.CharField(blank=True, db_column='CPU', max_length=100, null=True)),
                ('cpu序列号', models.CharField(blank=True, db_column='CPU序列号', max_length=100, null=True)),
                ('主板', models.CharField(blank=True, max_length=100, null=True)),
                ('操作系统', models.CharField(blank=True, max_length=100, null=True)),
                ('显卡', models.CharField(blank=True, max_length=100, null=True)),
                ('硬盘', models.CharField(blank=True, max_length=100, null=True)),
                ('硬盘序列号', models.CharField(blank=True, max_length=100, null=True)),
                ('内存', models.CharField(blank=True, max_length=100, null=True)),
                ('内存插槽', models.CharField(blank=True, max_length=50, null=True)),
                ('ip', models.CharField(blank=True, db_column='IP', max_length=100, null=True)),
                ('mac', models.CharField(blank=True, db_column='MAC', max_length=100, null=True)),
                ('购买日期', models.DateTimeField(blank=True, null=True)),
                ('管理人', models.CharField(blank=True, max_length=50, null=True)),
                ('电脑名称', models.CharField(blank=True, max_length=50, null=True)),
                ('删除标记', models.CharField(blank=True, max_length=10, null=True)),
                ('贴纸编码', models.CharField(blank=True, max_length=50, null=True)),
                ('备注', models.CharField(blank=True, max_length=200, null=True)),
                ('制单人', models.CharField(blank=True, max_length=50, null=True)),
                ('制单日期', models.DateTimeField(blank=True, null=True)),
                ('更新人', models.CharField(blank=True, max_length=50, null=True)),
                ('更新日期', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'IT资产',
                'managed': False,
            },
        ),
    ]
