# Generated by Django 2.1.15 on 2020-06-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoWeb_network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名称', models.CharField(blank=True, max_length=50, null=True)),
                ('位置', models.CharField(blank=True, max_length=50, null=True)),
                ('账号1', models.CharField(blank=True, max_length=100, null=True)),
                ('密码1', models.CharField(blank=True, max_length=100, null=True)),
                ('账号2', models.CharField(blank=True, max_length=100, null=True)),
                ('密码2', models.CharField(blank=True, max_length=100, null=True)),
                ('明细1', models.CharField(blank=True, max_length=100, null=True)),
                ('明细2', models.CharField(blank=True, max_length=100, null=True)),
                ('明细3', models.CharField(blank=True, max_length=100, null=True)),
                ('明细4', models.CharField(blank=True, max_length=100, null=True)),
                ('明细5', models.CharField(blank=True, max_length=100, null=True)),
                ('明细6', models.CharField(blank=True, max_length=100, null=True)),
                ('明细7', models.CharField(blank=True, max_length=100, null=True)),
                ('明细8', models.CharField(blank=True, max_length=100, null=True)),
                ('是否隐藏', models.IntegerField(blank=True, null=True)),
                ('备注', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'django_web_公司网络地址',
                'managed': True,
            },
        ),
    ]
