# Generated by Django 2.1.15 on 2020-06-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_NA_info_s', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoweb_network',
            name='卡片标识',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='djangoweb_network',
            name='卡片类型',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='djangoweb_network',
            name='费用',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
