# Generated by Django 2.1.15 on 2020-05-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('appname', models.CharField(blank=True, max_length=50, null=True)),
                ('apppage', models.CharField(blank=True, max_length=50, null=True)),
                ('host', models.CharField(blank=True, db_column='Host', max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('date2', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_web_login记录',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Xtyh',
            fields=[
                ('用户编号', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('用户姓名', models.CharField(blank=True, max_length=30, null=True)),
                ('部门', models.CharField(blank=True, max_length=20, null=True)),
                ('密码', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(max_length=200)),
                ('背景图片', models.CharField(max_length=50)),
                ('公司名称', models.CharField(max_length=50)),
                ('钉钉id', models.CharField(db_column='钉钉ID', max_length=50)),
                ('备注', models.CharField(max_length=50)),
                ('制单人', models.CharField(max_length=20)),
                ('制单人_name', models.CharField(blank=True, max_length=30, null=True)),
                ('制单日期', models.DateTimeField()),
                ('更新人', models.CharField(max_length=20)),
                ('更新人_name', models.CharField(blank=True, max_length=30, null=True)),
                ('更新日期', models.DateTimeField()),
                ('失效标志', models.BooleanField()),
                ('是否可以查看所有客户资料', models.BooleanField()),
            ],
            options={
                'db_table': '系统用户',
                'managed': True,
            },
        ),
    ]
